name: Rest-api with flask

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: making checkout
        uses: actions/checkout@v4

      - name: setting up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: installing pytest
        run: pip install pytest