name: Rest-api with flask

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: making checkout
        uses: actions/checkout@v4

      - name: setting up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: installing pytest
        run: pip install pytest

      - name: installing flask
        run: pip install Flask

      - name: installing sqlalchemy
        run: pip3 install flask_sqlalchemy

      - name: installing mysql connector
        run: pip3 install mysql-connector-python

      - name: running tests
        run: pytest test_app.py

      - name: printing out in console
        run: echo "compilacion  exitosa"